version: "3.9"

services:
  k8s-postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: sohrab
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: api_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  k8s-redis:
    image: redis:7
    restart: always
    ports:
      - "6374:6379"

  app:
    build: .
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - k8s-postgres
      - k8s-redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: ["air"]

volumes:
  postgres_data:
