version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: kubico-postgres
    environment:
      POSTGRES_USER: minik8s
      POSTGRES_PASSWORD: minik8s123
      POSTGRES_DB: minik8s
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minik8s"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
